Module = ""
Interactive = ""
Expression = ""
FunctionType = ""
FunctionDef = "def"
AsyncFunctionDef = ""
ClassDef = "class"
Return = "return"
Delete = ""
Assign = ""
AugAssign = ""
AnnAssign = ""
For = "for"
AsyncFor = ""
While = "while"
If = "if"
With = ""
AsyncWith = ""
Match = ""
Raise = ""
Try = ""
TryStar = ""
Assert = ""
Import = ""
ImportFrom = ""
Global = ""
Nonlocal = ""
Expr = ""
Pass = ""
Break = ""
Continue = ""
BoolOp = ""
NamedExpr = ""
BinOp = ""
UnaryOp = ""
Lambda = ""
IfExp = ""
Dict = ""
Set = ""
ListComp = ""
SetComp = ""
DictComp = ""
GeneratorExp = ""
Await = ""
Yield = ""
YieldFrom = ""
Compare = ""
Call = ""
FormattedValue = ""
JoinedStr = ""
Constant = ""
Attribute = ""
Subscript = ""
Starred = ""
Name = ""
List = ""
Tuple = ""
Slice = ""
Load = ""
Store = ""
Del = ""
And = ""
Or = ""
Add = ""
Sub = ""
Mult = ""
MatMult = ""
Div = ""
Mod = ""
Pow = ""
LShift = ""
RShift = ""
BitOr = ""
BitXor = ""
BitAnd = ""
FloorDiv = ""
Invert = ""
Not = ""
UAdd = ""
USub = ""
Eq = ""
NotEq = ""
Lt = ""
LtE = ""
Gt = ""
GtE = ""
Is = ""
IsNot = ""
In = ""
NotIn = ""
ExceptHandler = ""
MatchValue = ""
MatchSingleton = ""
MatchSequence = ""
MatchMapping = ""
MatchClass = ""
MatchStar = ""
MatchAs = ""
MatchOr = ""
TypeIgnore = ""
arguments = ""
arg = ""
keyword = ""